sourceMapProviders
skbkontur/frontreport pull request #3
Opened 2018-01-10 07:34 UTC by kamaev

2018-01-10 08:07 UTC, beevee requested changes

2018-01-10 08:07 UTC, beevee commented on cmd/frontreport/main.go
> +		SourceMapProviders string `short:"t" long:"sm-providers" description:"trusted sourcemap providers (regular expression)" env:"FRONTREPORT_PROVIDERS"`
Может, вместо providers лучше написать whitelist? Для единообразия с DomainWhitelist и ServiceWhitelist.

А еще в env надо тоже написать слово sourcemap, а то непонятно будет без контекста.

2018-01-10 08:07 UTC, beevee commented on cmd/frontreport/main.go
> +		SourceMapProviders string `short:"t" long:"sm-providers" description:"trusted sourcemap providers (regular expression)" env:"FRONTREPORT_PROVIDERS"`
А еще в description нужно написать, что будет, если не указать этот параметр.

2018-01-10 08:07 UTC, beevee commented on cmd/frontreport/main.go
> +		sourceMapProviders = ".*\\.?localhost[^.]*"
Здесь нужна гораздо жестче регулярка. Эту легко взломать, например: `http://evil.com/myrequest#\localhost` пройдет.

2018-01-10 08:07 UTC, beevee commented on sourcemap/sourcemap.go
> +	if matched, _ := regexp.MatchString(p.Providers, urlToCheck); matched {
Возможно, быстрее будет, если заранее скомпилировать регулярку, а не парсить каждый раз из строки.

2018-01-10 11:40 UTC, kamaev commented on cmd/frontreport/main.go
> +		SourceMapProviders string `short:"t" long:"sm-providers" description:"trusted sourcemap providers (regular expression)" env:"FRONTREPORT_PROVIDERS"`
fixed

2018-01-10 11:40 UTC, kamaev commented on cmd/frontreport/main.go
> +		sourceMapProviders = ".*\\.?localhost[^.]*"
fixed

2018-01-10 11:41 UTC, kamaev commented on sourcemap/sourcemap.go
> +	if matched, _ := regexp.MatchString(p.Providers, urlToCheck); matched {
fixed, добавил поле trustedURLRegexp, к исходному Providers обращаюсь как при компилировании, так и при создании сообщения об ошибке

2018-01-10 12:40 UTC, beevee requested changes

2018-01-10 12:40 UTC, beevee commented on cmd/frontreport/main.go
> +	sourceMapProviders := opts.SourceMapWhitelist
Давай вообще везде providers переименуем? Мне кажется, это слово здесь с толку сбивает.

2018-01-10 12:40 UTC, beevee commented on cmd/frontreport/main.go
> +		sourceMapProviders = "^(http|https)://localhost[^.]*"
Ты недооцениваешь хакеров :))

`http://localhost@evil.com/foo` сматчится.

2018-01-11 06:54 UTC, beevee approved these changes

2018-01-11 06:54 UTC, merged